### Create a new user
POST http://localhost:8000/user
Content-Type: application/json

{
  "username": "benho1",
  "password": "securepas1sword",
  "email": "meenh@o.dev",
  "role": "buyer"
}

### Get a user by ID
GET http://localhost:8080/user/get?id=60d5f9b8f8d2e2a5d4e8b456